### ISSUE TITLE
Deciding to Backend Layer Design

### ISSUE THREAD

**Issue by husamettinarabaci** [Ubn-Jr/hirob-docs#6]
What is the best arch and language for the backend layer? I think projects and infrastructure depend on that. What is our chosen?

**Comment by Sddilora** [comment]
I'm facing a decision, and I highly value your input. I'm uncertain about whether to use a traditional SQL database or a NoSQL solution like Firestore for our project's database. Your insights and advice would be greatly appreciated and will play a significant role in our backend development.

**Comment by husamettinarabaci** [comment]
I am thinking about this stack. It could change a little bit. We can discuss it on the "hirob-be" project and I've created a repository that fits your recommendation.

**Comment by Sddilora** [comment]
okay
